/// <reference types="esbuild" />
import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import inlineImportPlugin from "esbuild-plugin-inline-import";

const prod = (process.argv[2] === "production");
const test = ["test", "test-dev"].includes(process.argv[2]);
const dev = process.argv[2] === "test-dev" || process.argv.length < 3;
const entryPoints = test ? ["test/src/main.ts"] : ["src/main.ts"];
const debugString = prod ? "app.debugMode(true);" : "";
const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
` + debugString;

/** @type {import('esbuild').BuildOptions} */
const args = {
	banner: {
		js: banner,
	},
	entryPoints,
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/closebrackets",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/comment",
		"@codemirror/fold",
		"@codemirror/gutter",
		"@codemirror/highlight",
		"@codemirror/history",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/matchbrackets",
		"@codemirror/panel",
		"@codemirror/rangeset",
		"@codemirror/rectangular-selection",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/stream-parser",
		"@codemirror/text",
		"@codemirror/tooltip",
		"@codemirror/view",
		"@lezer/highlight",
		...builtins],
	format: "cjs",
	target: "es2016",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	minify: prod,
	treeShaking: true,
	outfile: "main.js",
	plugins: [
		inlineImportPlugin()
	]
};

if (dev) {
	const ctx = await esbuild.context(args);
	ctx.watch().catch(() => process.exit(1));
}
else {
	esbuild.build(args).catch(() => process.exit(1));
}
